# Generated by Django 2.2.5 on 2020-12-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201223_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(blank=True, choices=[('usd', 'USD'), ('euro', 'EURO')], max_length=4),
        ),
    ]
